name: CI (.NET 9)

on:
  push:
    branches: ["main", "develop", "feature/**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - ".gitignore"
  pull_request:
    branches: ["main", "develop"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"
          

      - name: Restore (solution)
        run: dotnet restore ./APIGenerica.sln

      - name: Build (solution)
        run: dotnet build ./APIGenerica.sln -c Release --no-restore

      - name: Test (solution)
        run: dotnet test ./APIGenerica.sln -c Release --no-build
